services:
  db:
    image: postgres:16
    container_name: gym_bot_db
    restart: always
    ports:
      - '9981:5432' # open to my Group
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: gym_bot_db
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - core-infra

  app:
    image: "${APP_IMAGE}:${APP_TAG}"
    restart: always
    container_name: gym_bot_app
    volumes:
      - ./sa.json:/app/app/sa.json:ro
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db:5432/gym_bot_db
      GOOGLE_SHEET_ID: ${GOOGLE_SHEET_ID}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    ports:
      - "5400:5400"
    networks:
      - core-infra
    depends_on:
      - db

networks:
  core-infra:
    external: true