# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-06-14T03:57:37+00:00

from __future__ import annotations

from datetime import date as date_aliased
from datetime import datetime
from enum import Enum, StrEnum

from pydantic import BaseModel, ConfigDict, Field, constr


class Error(BaseModel):
    detail: str


class TelegramWebAppAuthRequest(BaseModel):
    initData: str = Field(
        ..., description='Raw Telegram Web App initData query string.'
    )


class TelegramLoginRequest(BaseModel):
    id: int
    first_name: str
    last_name: str | None = None
    username: str | None = None
    photo_url: str | None = None
    auth_date: int
    hash: str


class AdminAuthRequest(BaseModel):
    username: str
    password: str


class Role(StrEnum):
    user = 'user'
    admin = 'admin'


class SessionIdentity(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    sub: str = Field(
        ..., description='Subject — the user id (Telegram id) or admin username.'
    )
    role: Role | None = None


class User(BaseModel):
    id: int = Field(..., description='Telegram user id.')
    first_name: str | None = None
    lastname: str | None = None
    username: str | None = None
    bio: str | None = None
    registration_date: datetime | None = None
    last_interaction: datetime | None = None


class UserRegistration(BaseModel):
    first_name: str | None = None
    lastname: str | None = None
    username: str | None = None
    bio: str | None = None


class Resolution(Enum):
    created = 'created'
    unhidden = 'unhidden'
    existing = 'existing'


class Muscle(BaseModel):
    id: int
    name: str
    is_global: bool | None = Field(
        None,
        description="True for the shared catalog; false for a user's private muscle.",
    )
    created_by: int | None = Field(
        None, description='Owning user id for a private muscle; null for global.'
    )
    is_mine: bool | None = Field(
        None,
        description="True when this is the caller's own custom record (rename/delete allowed); false for global catalog items (hide only).\n",
    )
    resolution: Resolution | None = Field(
        None,
        description="Only set on create responses: 'created' = a new row; 'unhidden' = an existing hidden item was silently unhidden; 'existing' = the item already existed and visible (no duplicate created). Absent/null on list and read responses.\n",
    )


class MuscleCreate(BaseModel):
    name: constr(
        pattern=r'^[A-Za-z0-9À-ÖØ-öø-ÿА-яЁё \-\'.,()/&+°]+$',
        min_length=1,
        max_length=30,
    ) = Field(
        ...,
        description="Muscle group name. Normalized (trim + collapse internal whitespace) then validated. Allowed: Unicode letters/digits, space, and - ' . , ( ) / & + ° (degree). See docs/validation.md (Name rules).\n",
    )


class MuscleRename(BaseModel):
    name: constr(
        pattern=r'^[A-Za-z0-9À-ÖØ-öø-ÿА-яЁё \-\'.,()/&+°]+$',
        min_length=1,
        max_length=30,
    ) = Field(
        ...,
        description="New muscle group name. Normalized (trim + collapse internal whitespace) then validated. Allowed: Unicode letters/digits, space, and - ' . , ( ) / & + ° (degree). See docs/validation.md (Name rules).\n",
    )


class Exercise(BaseModel):
    id: int
    name: str
    muscle: int = Field(..., description='Owning muscle id.')
    is_global: bool | None = None
    created_by: int | None = None
    is_mine: bool | None = Field(
        None,
        description="True when this is the caller's own custom record (rename/delete allowed); false for global catalog items (hide only).\n",
    )
    resolution: Resolution | None = Field(
        None,
        description="Only set on create responses: 'created' = a new row; 'unhidden' = an existing hidden item was silently unhidden; 'existing' = the item already existed and visible (no duplicate created). Absent/null on list and read responses.\n",
    )


class MatchReason(StrEnum):
    exact = 'exact'
    prefix = 'prefix'
    alias = 'alias'
    fuzzy = 'fuzzy'


class ExerciseCandidate(BaseModel):
    id: int = Field(..., description='Canonical exercise id (mirrors Exercise.id).')
    name: str = Field(
        ..., description='Display name of the exercise (mirrors Exercise.name).'
    )
    muscle: int = Field(..., description='Owning muscle id (mirrors Exercise.muscle).')
    muscle_name: str = Field(
        ..., description='Owning muscle name, denormalized for display.'
    )
    match_reason: MatchReason = Field(
        ...,
        description="Why the candidate matched: 'exact' = exact name_key, 'prefix' = name_key prefix, 'alias' = matched a (lang-aware) exercise_alias, 'fuzzy' = pg_trgm similarity (typo tolerance).\n",
    )
    score: float = Field(..., description='Ranking score; higher is a better match.')


class ExerciseCreate(BaseModel):
    name: constr(
        pattern=r'^[A-Za-z0-9À-ÖØ-öø-ÿА-яЁё \-\'.,()/&+°]+$',
        min_length=1,
        max_length=40,
    ) = Field(
        ...,
        description="Exercise name. Normalized (trim + collapse internal whitespace) then validated. Allowed: Unicode letters/digits, space, and - ' . , ( ) / & + ° (degree). See docs/validation.md (Name rules).\n",
    )
    muscle_name: constr(min_length=1) = Field(
        ...,
        description='Owning muscle group name — reference to an existing record, normalized only (trim + collapse internal whitespace), not length/char-bound. Must match an existing muscle; non-matching values 404 at the DB. See docs/validation.md (Name rules — Create vs lookup).\n',
    )


class ExerciseRename(BaseModel):
    name: constr(
        pattern=r'^[A-Za-z0-9À-ÖØ-öø-ÿА-яЁё \-\'.,()/&+°]+$',
        min_length=1,
        max_length=40,
    ) = Field(
        ...,
        description="New exercise name. Normalized (trim + collapse internal whitespace) then validated. Allowed: Unicode letters/digits, space, and - ' . , ( ) / & + ° (degree). See docs/validation.md (Name rules).\n",
    )


class ExerciseMove(BaseModel):
    muscle_id: int = Field(
        ..., description='Id of the muscle to move the exercise under.'
    )


class AdminExerciseCreate(BaseModel):
    name: constr(
        pattern=r'^[A-Za-z0-9À-ÖØ-öø-ÿА-яЁё \-\'.,()/&+°]+$',
        min_length=1,
        max_length=40,
    ) = Field(
        ...,
        description="Exercise name. Normalized (trim + collapse internal whitespace) then validated. Allowed: Unicode letters/digits, space, and - ' . , ( ) / & + ° (degree). See docs/validation.md (Name rules).\n",
    )
    muscle: int


class Training(BaseModel):
    id: str = Field(..., description='Server-assigned record id.')
    date: datetime
    user_id: int
    muscle_id: int
    exercise_id: int
    set: int
    weight: float
    reps: float


class TrainingCreate(BaseModel):
    muscle_name: constr(min_length=1) = Field(
        ...,
        description='Muscle group name — reference to an existing record, normalized only (trim + collapse internal whitespace), not length/char-bound. See docs/validation.md (Name rules — Create vs lookup).\n',
    )
    exercise_name: constr(min_length=1) = Field(
        ...,
        description='Exercise name — reference to an existing record, normalized only (trim + collapse internal whitespace), not length/char-bound. See docs/validation.md (Name rules — Create vs lookup).\n',
    )
    set: int
    weight: float
    reps: float
    date: date_aliased | None = Field(
        None,
        description='Optional calendar day to log the set on (date part only; naive-tolerant per GYM-30). When provided, the set is recorded on that day (retroactive add). When omitted, the server uses now() — unchanged, backward-compatible.\n',
    )


class TrainingUpdate(BaseModel):
    weight: float
    reps: float


class TrainingMove(BaseModel):
    date: date_aliased | None = Field(
        None,
        description='Target calendar day to move the set to (date part only; naive-tolerant per GYM-30). Omit to keep the set on its current day.\n',
    )
    muscle_name: str | None = Field(
        None,
        description='Target muscle group name — reference to an existing record, normalized only (trim + collapse internal whitespace), not length/char-bound. Required together with exercise_name when moving to another exercise. See docs/validation.md (Name rules — Create vs lookup).\n',
    )
    exercise_name: str | None = Field(
        None,
        description='Target exercise name — reference to an existing record, normalized only (trim + collapse internal whitespace), not length/char-bound. Required together with muscle_name when moving to another exercise. See docs/validation.md (Name rules — Create vs lookup).\n',
    )


class TrainingDay(BaseModel):
    date: date_aliased
    muscles: list[str] = Field(
        ..., description='Names of the muscle groups trained that day.'
    )
    exercises_count: int = Field(
        ..., description='Distinct exercises trained that day.'
    )
    sets_count: int = Field(..., description='Total sets recorded that day.')
    has_pr: bool = Field(
        ...,
        description='True when the day holds the caller\'s current all-time max-weight set of at least one exercise (GYM-136). Semantic is "current max", not "was a PR when logged": the marker reflects today\'s standing weight records, so a later heavier set moves the marker to its own day, and a tie marks every tying day.\n',
    )


class PrKind(Enum):
    weight = 'weight'
    reps = 'reps'
    NoneType_None = None


class TrainingSet(BaseModel):
    training_id: str = Field(..., description='Server-assigned record id of the set.')
    set: int
    weight: float
    reps: float
    is_pr: bool = Field(
        ...,
        description="True when this set holds the caller's current all-time max weight for its exercise (a standing personal record), per GYM-141. Server-computed; not 'was a PR when logged'.",
    )
    pr_kind: PrKind | None = Field(
        ...,
        description="Which kind of personal record this set is, per GYM-155. Null (or absent) when is_pr is false. 'weight' when the set is a strict weight PR — a never-before-lifted weight, including the first-ever set of the exercise; 'reps' when it is a strict reps-at-weight PR. The two values are mutually exclusive. Server-computed.",
    )


class TrainingDayExercise(BaseModel):
    exercise_id: int
    exercise_name: str
    muscle_name: str
    sets: list[TrainingSet]


class TrainingDayDetail(BaseModel):
    date: date_aliased
    exercises: list[TrainingDayExercise]


class CompletedSets(BaseModel):
    sets: list[int] = Field(
        ...,
        description='Distinct set numbers already recorded for the exercise on the date.',
    )


class TrainingHistoryEntry(BaseModel):
    date: datetime
    set: int
    weight: float
    reps: float


class PersonalRecord(BaseModel):
    weight: float
    reps: float
    date: datetime


class LogSet(BaseModel):
    set: int
    weight: float
    reps: float


class LogContext(BaseModel):
    completed_sets: list[int] = Field(
        ..., description='Set numbers already logged on the date for this exercise.'
    )
    last_session_sets: list[LogSet] = Field(
        ..., description="The most recent prior session's sets, ordered by set."
    )
    pr: PersonalRecord | None = Field(
        ..., description='The personal record, or null when no history exists.'
    )


class MaxReps(BaseModel):
    max_reps: float | None = Field(
        ...,
        description='Maximum reps at the queried weight, or null when no history exists.',
    )


class TopExercise(BaseModel):
    name: str
    frequency: int = Field(
        ..., description='Number of recorded sessions for the exercise.'
    )


class RecentExercise(BaseModel):
    muscle_name: str
    exercise_name: str
    last_weight: float
    last_reps: float
    last_date: date_aliased


class TopMuscle(BaseModel):
    name: str
    frequency: int = Field(
        ..., description='Number of recorded sessions for the muscle.'
    )


class ActivityDay(BaseModel):
    date: date_aliased
    sets_count: int = Field(..., description='Number of sets recorded on this day.')


class AnalyticsSummary(BaseModel):
    exercises: int = Field(..., description='Distinct exercises ever logged.')
    sets: int = Field(..., description='Total sets recorded.')
    prs: int = Field(..., description='Count of personal records.')
    current_streak: int = Field(
        ..., description='Current consecutive-day training streak.'
    )


class ExercisePoint(BaseModel):
    date: date_aliased
    weight: float
    reps: float


class ExerciseSetSeries(BaseModel):
    set: int
    points: list[ExercisePoint]


class ExerciseProgress(BaseModel):
    series: list[ExerciseSetSeries]


class SessionVolume(BaseModel):
    date: date_aliased
    volume: float = Field(
        ..., description='Sum of weight×reps across all sets of the session.'
    )


class E1rmPoint(BaseModel):
    date: date_aliased
    e1rm: float = Field(
        ..., description="max(weight × (1 + reps/30)) across the session's sets."
    )


class ExerciseTrend(BaseModel):
    last_session: SessionVolume | None = Field(
        ..., description='The most recent session, or null when no history exists.'
    )
    prev_session: SessionVolume | None = Field(
        ..., description='The session before the most recent one, or null.'
    )
    e1rm_trend: list[E1rmPoint] = Field(
        ...,
        description='Per-session max-e1RM points within the window, date ascending.',
    )


class WeekStats(BaseModel):
    sets: int = Field(..., description='Number of sets recorded in the week.')
    volume: float = Field(..., description="Sum of weight×reps across the week's sets.")


class WeekCompare(BaseModel):
    this_week: WeekStats
    last_week: WeekStats


class StaticData(BaseModel):
    sets: list[str]
    weights: list[str]
    reps: list[str]


class AuthResponse(BaseModel):
    token: str
    user: SessionIdentity
