# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-06-01T13:18:31+00:00

from __future__ import annotations

from enum import StrEnum

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Error(BaseModel):
    detail: str


class TelegramWebAppAuthRequest(BaseModel):
    initData: str = Field(
        ..., description='Raw Telegram Web App initData query string.'
    )


class TelegramLoginRequest(BaseModel):
    id: int
    first_name: str
    last_name: str | None = None
    username: str | None = None
    photo_url: str | None = None
    auth_date: int
    hash: str


class AdminAuthRequest(BaseModel):
    username: str
    password: str


class Role(StrEnum):
    user = 'user'
    admin = 'admin'


class SessionIdentity(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    sub: str = Field(
        ..., description='Subject — the user id (Telegram id) or admin username.'
    )
    role: Role | None = None


class User(BaseModel):
    id: int = Field(..., description='Telegram user id.')
    first_name: str | None = None
    lastname: str | None = None
    username: str | None = None
    bio: str | None = None
    registration_date: AwareDatetime | None = None
    last_interaction: AwareDatetime | None = None


class UserRegistration(BaseModel):
    first_name: str | None = None
    lastname: str | None = None
    username: str | None = None
    bio: str | None = None


class Muscle(BaseModel):
    id: int
    name: str
    is_global: bool | None = Field(
        None,
        description="True for the shared catalog; false for a user's private muscle.",
    )
    created_by: int | None = Field(
        None, description='Owning user id for a private muscle; null for global.'
    )


class MuscleCreate(BaseModel):
    name: str


class Exercise(BaseModel):
    id: int
    name: str
    muscle: int = Field(..., description='Owning muscle id.')
    is_global: bool | None = None
    created_by: int | None = None


class ExerciseCreate(BaseModel):
    name: str
    muscle_name: str


class AdminExerciseCreate(BaseModel):
    name: str
    muscle: int


class Training(BaseModel):
    id: str = Field(..., description='Server-assigned record id.')
    date: AwareDatetime
    user_id: int
    muscle_id: int
    exercise_id: int
    set: int
    weight: float
    reps: float


class TrainingCreate(BaseModel):
    muscle_name: str
    exercise_name: str
    set: int
    weight: float
    reps: float


class TrainingUpdate(BaseModel):
    weight: float
    reps: float


class CompletedSets(BaseModel):
    sets: list[int] = Field(
        ...,
        description='Distinct set numbers already recorded for the exercise on the date.',
    )


class TrainingHistoryEntry(BaseModel):
    date: AwareDatetime
    set: int
    weight: float
    reps: float


class PersonalRecord(BaseModel):
    weight: float
    reps: float
    date: AwareDatetime


class MaxReps(BaseModel):
    max_reps: float | None = Field(
        ...,
        description='Maximum reps at the queried weight, or null when no history exists.',
    )


class TopExercise(BaseModel):
    name: str
    frequency: int = Field(
        ..., description='Number of recorded sessions for the exercise.'
    )


class StaticData(BaseModel):
    sets: list[str]
    weights: list[str]
    reps: list[str]


class AuthResponse(BaseModel):
    token: str
    user: SessionIdentity
