---
- name: Deploy application
  hosts: app
  become: yes
  vars:
    work_dir: /opt/gym-bot
  
  tasks:
    - name: Ensure home directory exists
      tags: ["app"]
      ansible.builtin.file:
        path: "{{ work_dir }}"
        state: directory
        mode: '0755'
      with_items:
        - "{{ work_dir }}"
        - "{{ work_dir }}/db_data"
    
    - name: Prepare environment variables
      tags: ["app", "env"]
      ansible.builtin.copy:
        dest: "{{ work_dir }}/.env"
        content: |
          APP_IMAGE={{ lookup('env', 'DOCKER_IMAGE') }}
          APP_TAG={{ lookup('env', 'DOCKER_TAG') }}
          GOOGLE_SHEET_ID={{ lookup('env', 'GOOGLE_SHEET_ID') }}
          TELEGRAM_BOT_TOKEN={{ lookup('env', 'TELEGRAM_BOT_TOKEN') }}
    
    - name: Prepare sa.json
      tags: ["app"]
      ansible.builtin.copy:
        dest: "{{ work_dir }}/sa.json"
        content: |
          {{ lookup('env', 'SA') }}
    
    - name: Ensure init.sql exists
      tags: ["app"]
      ansible.builtin.copy:
        src: "{{inventory_dir}}/files/init.sql"
        dest: "{{ work_dir }}/init.sql"

    - name: Ensure docker-compose.yml is updated
      tags: ["app"]
      ansible.builtin.template:
        src: "{{inventory_dir}}/files/docker-compose.yaml"
        dest: "{{ work_dir }}/docker-compose.yml"
      register: _docker_compose
    
    - name: Check container
      # when: _docker_compose is changed
      tags: ["app"]
      block:
        - name: Ensure app container is absent
          community.docker.docker_compose_v2:
            project_src: "{{ work_dir }}"
            state: absent

        - name: Ensure app container is running
          community.docker.docker_compose_v2:
            project_src: "{{ work_dir }}"
            pull: always
            state: present
          register: _docker_compose

