name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Build and push Docker image
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/gym-bot
          IMAGE_TAG: latest
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG
      
      # - name: Deploy with Ansible
      #   run: |
      #     sudo apt-get update && sudo apt-get install -y ansible
      #     ansible-playbook -i inventory deploy.yml